#!/usr/bin/env bash
# install.sh — set up the krambuhl/agents marketplace on this machine.
#
# Wires three things:
#   1. ~/.agents/{skills,agents,cli,learnings} symlinks into this clone
#      (per-item for skills + agents so npx-installed skills can coexist;
#      whole-dir for cli + learnings since they own the namespace)
#   2. ~/.claude/{skills,agents}/<name> symlink farm back into ~/.agents/
#      (relative `../../.agents/...` paths — matches the skills CLI convention)
#   3. bin/{guild,griot,loom} shims inside this clone (the chicken-and-egg
#      bootstrap, so `bin/loom adopt` is invokable from the marketplace itself
#      on first use, before any consumer project has its own bin/ shims)
#
# Idempotent. Safe to re-run after `git pull`. Refuses to clobber non-symlink
# entries in ~/.agents/ or ~/.claude/ — those belong to other tools
# (skills CLI installs, hand-authored content) and the install is not
# permitted to destroy them.
#
# Usage: ./install.sh
#
# Resolves the marketplace clone's path via `pwd` so the install works
# wherever the user clones the repo (no hardcoded ~/Sites/agents assumption).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MARKETPLACE="$SCRIPT_DIR"

echo "==> installing krambuhl/agents marketplace from $MARKETPLACE"

# ----- Step 1: ~/.agents/* symlinks -----

mkdir -p "$HOME/.agents/skills" "$HOME/.agents/agents"

# cli + learnings + docs: single whole-dir symlink each. They own the
# namespace at ~/.agents/<top>/, so a directory-level symlink is the
# clean shape. (docs is whole-dir today; switch to per-item if a
# consumer ever needs to drop in their own docs alongside the
# marketplace ones.)
for top in cli learnings docs; do
  link="$HOME/.agents/$top"
  target="$MARKETPLACE/$top"
  if [[ -L "$link" ]]; then
    rm -f "$link"
  elif [[ -e "$link" ]]; then
    echo "  skip  ~/.agents/$top (exists, not a symlink — refusing to clobber)"
    continue
  fi
  ln -s "$target" "$link"
  echo "  link  ~/.agents/$top -> $target"
done

# skills + agents: per-item symlinks. This shape lets npx-installed skills
# (real directories from the skills CLI) coexist with marketplace-installed
# skills (symlinks back into this clone) under the same ~/.agents/skills/.
link_per_item() {
  local subdir="$1"
  local pattern="$2"
  local count=0
  shopt -s nullglob
  for entry in "$MARKETPLACE/$subdir"/$pattern; do
    [[ -e "$entry" ]] || continue
    local name; name=$(basename "$entry")
    local link="$HOME/.agents/$subdir/$name"
    if [[ -L "$link" ]]; then
      rm -f "$link"
    elif [[ -e "$link" ]]; then
      echo "  skip  ~/.agents/$subdir/$name (exists, not a symlink)"
      continue
    fi
    ln -s "$entry" "$link"
    count=$((count + 1))
  done
  shopt -u nullglob
  echo "  link  $count items in ~/.agents/$subdir/"
}

link_per_item skills '*/'
link_per_item agents '*.md'

# ----- Step 2: ~/.claude/* symlink farm -----

mkdir -p "$HOME/.claude/skills" "$HOME/.claude/agents"

# Per-item symlinks into ~/.claude/, with RELATIVE targets (../../.agents/...).
# This matches the skills-CLI convention and means the symlinks remain valid
# regardless of the absolute path of $HOME (handy across Mac/Linux orb boxes).
farm_into_claude() {
  local subdir="$1"
  local pattern="$2"
  local rel_prefix="$3"  # e.g. ../../.agents/skills
  local count=0
  shopt -s nullglob
  for entry in "$HOME/.agents/$subdir"/$pattern; do
    [[ -e "$entry" ]] || continue
    local name; name=$(basename "$entry")
    local link="$HOME/.claude/$subdir/$name"
    if [[ -L "$link" ]]; then
      rm -f "$link"
    elif [[ -e "$link" ]]; then
      echo "  skip  ~/.claude/$subdir/$name (exists, not a symlink)"
      continue
    fi
    ln -s "$rel_prefix/$name" "$link"
    count=$((count + 1))
  done
  shopt -u nullglob
  echo "  farm  $count items in ~/.claude/$subdir/"
}

farm_into_claude skills '*/'   "../../.agents/skills"
farm_into_claude agents '*.md' "../../.agents/agents"

# ----- Step 3: chicken-and-egg bin shims inside the marketplace clone -----
#
# Without this, the very first `bin/loom adopt` (run inside a consumer project
# that hasn't been framework-enabled yet) has nowhere to resolve. By creating
# bin/{guild,griot,loom} inside the marketplace clone, the user can
# always invoke the framework via $MARKETPLACE/bin/<cli> before any project
# is adopted. After `bin/loom adopt`, each project gets its own bin/<cli>
# shims pointing into ~/.agents/cli/ (i.e. back into this marketplace clone).
#
# These shims are regenerated on every install (idempotent), so a `git pull`
# + re-run picks up any tweaks to the shim shape without staleness risk.

mkdir -p "$MARKETPLACE/bin"

for cli in guild griot loom; do
  shim="$MARKETPLACE/bin/$cli"
  cat > "$shim" <<EOF
#!/usr/bin/env bash
# $cli — entry shim for the $cli CLI (marketplace-rooted chicken-and-egg copy).
# Resolves cli/$cli.ts relative to this shim. Generated by install.sh on
# every run; do not hand-edit (changes will be overwritten on re-install).
set -euo pipefail

SHIM_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
ENTRY="\$SHIM_DIR/../cli/$cli.ts"

if [[ ! -f "\$ENTRY" ]]; then
  echo "$cli-shim-error: entry not found at \$ENTRY" >&2
  exit 2
fi

exec node "\$ENTRY" "\$@"
EOF
  chmod +x "$shim"
done
echo "  bin   4 shims regenerated in $MARKETPLACE/bin/"

echo "==> done"
echo ""
echo "Next:"
echo "  - Adopt framework in a new project: cd <project> && $MARKETPLACE/bin/loom adopt"
echo "  - The skills CLI can also install individual skills: npx skills add krambuhl/agents@<skill-name>"
