import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { generateVerb } from './cli/verbs/guild/generate.ts';
import type { GuildCliContext } from './cli/verbs/guild/index.ts';

// Freshness gate for the COMMITTED generated panel.
//
// plugins/guild/agents/ holds runtime agent files. Most are emitted by
// `guild generate` (combinations + singletons + recipe members), but a
// small set of files are deliberately retained hand-authored
// (evaluator-base, evaluator-contract-fit, whiteboard-base). The
// retained set is NOT exhaustively listed here — the regen's own output
// is the source of truth for "is this name a generated agent?", and the
// test checks each generated name against committed content.
//
// Committing the generated tree (rather than gitignoring) buys this
// test: regenerate into a tmpdir and assert the committed copies are
// byte-identical. It fails the moment someone hand-edits a generated
// file or forgets to re-run `guild generate` after editing a source
// fragment / panel.manifest.toml / tools-map.toml — the same shape as a
// lockfile-freshness check. (Determinism — two regens agree — is proven
// in cli/verbs/guild/generate.test.ts; this guards committed-vs-regen.)
//
// Pre-Phase-7 the codegen output lived in agents/generated/ as a
// staging subdir alongside coexisting baked files. The U1 cutover moved
// the generated files to the agents/ root (their runtime home) and
// deleted the baked, so this test compares against the root directly,
// filtering by the regen's own emitted list.

const pluginRoot = dirname(fileURLToPath(import.meta.url)); // plugins/guild
const committedDir = join(pluginRoot, 'agents');
const ctx: GuildCliContext = { cwd: pluginRoot, stdin: '' };

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'guild-freshness-'));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe('committed generated panel is fresh', () => {
  it('matches a fresh regen byte-for-byte for every generated file', () => {
    const res = generateVerb(
      [`--source-dir=${pluginRoot}`, `--out=${tmp}`],
      ctx,
    );
    expect(res.exitCode).toBe(0);

    // The regen output is the authoritative list of generated names;
    // the committed root may carry additional retained hand-authored
    // files (evaluator-base, evaluator-contract-fit, whiteboard-base)
    // plus the personalities/ subdir, all of which this test ignores.
    const regen = readdirSync(tmp).filter((f) => f.endsWith('.md')).sort();
    expect(regen.length).toBeGreaterThan(0);

    for (const file of regen) {
      expect(readFileSync(join(committedDir, file), 'utf8')).toBe(
        readFileSync(join(tmp, file), 'utf8'),
      );
    }
  });

  it('every generated file carries the do-not-edit provenance banner', () => {
    const res = generateVerb(
      [`--source-dir=${pluginRoot}`, `--out=${tmp}`],
      ctx,
    );
    expect(res.exitCode).toBe(0);

    const regen = readdirSync(tmp).filter((f) => f.endsWith('.md'));
    for (const file of regen) {
      const content = readFileSync(join(committedDir, file), 'utf8');
      expect(content).toContain('<!-- GENERATED by `guild generate`');
    }
  });

  it('reviewers carry maxTurns: 5, planners do not, all carry model + tools', () => {
    const res = generateVerb(
      [`--source-dir=${pluginRoot}`, `--out=${tmp}`],
      ctx,
    );
    expect(res.exitCode).toBe(0);

    const regen = readdirSync(tmp).filter((f) => f.endsWith('.md'));
    for (const file of regen) {
      const content = readFileSync(join(committedDir, file), 'utf8');
      if (file.startsWith('evaluator-')) {
        expect(content).toMatch(/^maxTurns: 5$/m);
      } else if (file.startsWith('whiteboard-')) {
        expect(content).not.toMatch(/^maxTurns:/m);
      }
      expect(content).toMatch(/^model: inherit$/m);
      expect(content).toMatch(/^tools: .+$/m);
    }
  });
});
