import { mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { generateVerb } from './cli/verbs/guild/generate.ts';
import type { GuildCliContext } from './cli/verbs/guild/index.ts';

// Freshness gate for the COMMITTED generated panel.
//
// plugins/guild/agents/generated/ holds the runtime agent files emitted
// by `guild generate`. Committing them (rather than gitignoring) buys
// this test: regenerate into a tmpdir and assert the committed tree is
// byte-identical. It fails the moment someone hand-edits a generated
// file or forgets to re-run `guild generate` after editing a source
// fragment / panel.manifest.toml / tools-map.toml — the same shape as a
// lockfile-freshness check. (Determinism — two regens agree — is proven
// in cli/verbs/guild/generate.test.ts; this guards committed-vs-regen.)

const pluginRoot = dirname(fileURLToPath(import.meta.url)); // plugins/guild
const committedDir = join(pluginRoot, 'agents', 'generated');
const ctx: GuildCliContext = { cwd: pluginRoot, stdin: '' };

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'guild-freshness-'));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe('committed generated panel is fresh', () => {
  it('matches a fresh regen byte-for-byte (same files, same content)', () => {
    const res = generateVerb(
      [`--source-dir=${pluginRoot}`, `--out=${tmp}`],
      ctx,
    );
    expect(res.exitCode).toBe(0);

    const regen = readdirSync(tmp).sort();
    const committed = readdirSync(committedDir).sort();
    expect(committed).toEqual(regen);
    expect(committed.length).toBeGreaterThan(0);

    for (const file of committed) {
      expect(readFileSync(join(committedDir, file), 'utf8')).toBe(
        readFileSync(join(tmp, file), 'utf8'),
      );
    }
  });

  it('carries the do-not-edit provenance banner in every file', () => {
    for (const file of readdirSync(committedDir)) {
      const content = readFileSync(join(committedDir, file), 'utf8');
      expect(content).toContain('<!-- GENERATED by `guild generate`');
    }
  });

  it('reviewers carry maxTurns: 5, planners do not, all carry model + tools', () => {
    for (const file of readdirSync(committedDir)) {
      const content = readFileSync(join(committedDir, file), 'utf8');
      if (file.startsWith('evaluator-')) {
        expect(content).toMatch(/^maxTurns: 5$/m);
      } else if (file.startsWith('whiteboard-')) {
        expect(content).not.toMatch(/^maxTurns:/m);
      }
      expect(content).toMatch(/^model: inherit$/m);
      expect(content).toMatch(/^tools: .+$/m);
    }
  });
});
